PREFIX ec: <https://id.exergism.org/commons#>
PREFIX ex: <https://id.exergism.org/exergism#>
PREFIX ecl: <https://id.exergism.org/ecl#>

SELECT ?claim ?status
WHERE {
  ?claim a ex:Claim ; ec:status ?status .
  FILTER (?status IN ("candidate", "accepted", "disputed"))
  FILTER NOT EXISTS { ?claim ecl:evidenceFor ?evidence . }
  FILTER NOT EXISTS { ?claim ecl:evidenceAgainst ?counterEvidence . }
}
