PREFIX ec: <https://id.exergism.org/commons#>
PREFIX ex: <https://id.exergism.org/exergism#>
PREFIX ecl: <https://id.exergism.org/ecl#>

SELECT ?record ?target
WHERE {
  {
    ?record a ex:Claim ; ec:supersedes ?target .
    FILTER NOT EXISTS {
      ?target a ex:Claim ; ec:stableId ?targetId .
    }
  }
  UNION
  {
    ?record a ecl:EvidenceItem ; ec:supersedes ?target .
    FILTER NOT EXISTS {
      ?target a ecl:EvidenceItem ; ec:stableId ?targetId .
    }
  }
}
