PREFIX ec: <https://id.exergism.org/commons#>
PREFIX ecl: <https://id.exergism.org/ecl#>

SELECT ?subject ?predicate ?object WHERE {
  VALUES ?predicate {
    ecl:tracks
    ecl:partOf
    ecl:controls
    ecl:controlledBy
    ecl:participatesIn
    ecl:operates
    ecl:deploys
    ecl:materiallyBenefits
    ecl:targetsOrAffects
    ecl:remediates
    ecl:reviews
  }
  ?subject ?predicate ?object .
  FILTER (STRSTARTS(STR(?object), "https://id.exergism.org/ecl#"))
  FILTER NOT EXISTS { ?object ec:stableId ?stableId . }
}
