PREFIX ec: <https://id.exergism.org/commons#>
PREFIX ex: <https://id.exergism.org/exergism#>
PREFIX ecl: <https://id.exergism.org/ecl#>

SELECT ?claim ?predicate ?evidence
WHERE {
  ?claim a ex:Claim ; ?predicate ?evidence .
  VALUES ?predicate { ecl:evidenceFor ecl:evidenceAgainst }
  FILTER NOT EXISTS { ?evidence a ecl:EvidenceItem ; ec:stableId ?evidenceId . }
}
