PREFIX ec: <https://id.exergism.org/commons#>
PREFIX ex: <https://id.exergism.org/exergism#>
PREFIX ecl: <https://id.exergism.org/ecl#>

SELECT ?child ?parent ?reason WHERE {
  ?child ecl:partOf ?parent .
  {
    FILTER NOT EXISTS {
      ?child ec:stableId ?childId ; a ?childType .
      VALUES ?childType { ex:State ec:Organization ec:Person ex:Agency ecl:Institution }
    }
    BIND("invalid-or-unresolved-child-actor" AS ?reason)
  }
  UNION
  {
    FILTER NOT EXISTS {
      ?parent ec:stableId ?parentId ; a ?parentType .
      VALUES ?parentType { ex:State ec:Organization ec:Person ex:Agency ecl:Institution }
    }
    BIND("invalid-or-unresolved-parent-actor" AS ?reason)
  }
}
