PREFIX ex: <https://id.exergism.org/exergism#>
PREFIX ecl: <https://id.exergism.org/ecl#>

SELECT ?entry
WHERE {
  ?entry a ex:ScheduleEntry .
  FILTER NOT EXISTS { ?entry ecl:basedOnDecision ?decision . }
}
