PREFIX ec: <https://id.exergism.org/commons#>
PREFIX ex: <https://id.exergism.org/exergism#>
PREFIX ecl: <https://id.exergism.org/ecl#>

SELECT ?state ?predicate ?value WHERE {
  ?state a ex:State ; ?predicate ?value .
  FILTER (
    ?predicate = ecl:outcome ||
    ?predicate = ec:status ||
    REGEX(
      STR(?predicate),
      "(current.?governance|governance.?(status|outcome)|restriction.?status|restricted.?status|tier|provisional.?outcome)$",
      "i"
    )
  )
}
