PREFIX ex: <https://id.exergism.org/exergism#>
PREFIX ecl: <https://id.exergism.org/ecl#>

SELECT ?state ?predicate ?outcome WHERE {
  ?state a ex:State ; ?predicate ?outcome .
  ?outcome a ecl:GovernanceOutcome .
}
